#!/usr/bin/env python3
"""Authoring source of the Strategy H v1 templates (round-spec + run-spec).

Writes runtime/templates/strategy_h_v1_{round,run}_spec.template.json.  Every scientific field
comes from runtime/strategy_h_v1_counts.py, so the templates and the counts validator can never
drift apart; the two templates are generated together (one source of truth).  Only the three
registered round-spec placeholders ({{round_id}}, {{kanban_task_id}}, {{created_at_utc}}), the
seven registered run-spec placeholders and the fingerprint text are ever substituted at
instantiation.

usage: python3 runtime/_author_strategy_h_template.py [--family-json <path>] [--check]

--check writes nothing: it re-authors both documents in memory, proves that the ONLY
unsubstituted tokens are the registered placeholders, validates the round-spec with
runtime/strategy_h_v1_counts.py AND runtime/parameter_contract.py, validates the pair in the
form the production card will publish it (the seven run-spec placeholders substituted with
synthetic values, because a raw {{script_sha256}} cannot satisfy the sha256 pin check before
instantiation), and compares the regenerated bytes with the frozen files on disk (byte
stability).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import strategy_h_v1_counts as C  # noqa: E402
import parameter_contract as pc  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATES = os.path.join(HERE, "templates")
FAMILY_ID = C.FAMILY_ID
GRID_CASES = [{f: int(v) for f, v in zip(C.CASE_FIELDS, case)} for case in C.STRATEGY_CASES]
DCA_CELLS = [dict(zip(C.DCA_AXES, cell), base_quote=1000)
             for cell in C.product([C.DCA_GRID[a] for a in C.DCA_AXES])]
ROUND_PLACEHOLDERS = ["{{round_id}}", "{{kanban_task_id}}", "{{created_at_utc}}"]
RUN_PLACEHOLDERS = ["{{round_id}}", "{{run_id}}", "{{task_id}}", "{{created_at_utc}}",
                    "{{script_sha256}}", "{{engine_selfcheck_sha256}}", "{{round_spec_path}}"]
# Canonical instrument metadata of the four registered USD-M perpetual contracts, read from the
# read-only raw store binance/usdm/instruments/usdm-perp-instruments.json at pre-registration
# (the engine re-reads it at run time; nothing here is hard-coded into the engine).
INSTRUMENTS = {
    "BNBUSDT": {"id": "BNBUSDT-PERP.BINANCE", "type": "CryptoPerpetual",
                "base_currency": "BNB", "quote_currency": "USDT", "settlement_currency": "USDT",
                "is_inverse": False, "price_increment": 0.01, "size_increment": 0.01,
                "lot_size": "0.01", "maker_fee": 0.0002, "taker_fee": 0.0005,
                "margin_init": 0.1, "margin_maint": 0.1, "min_notional": "5.00000000 USDT",
                "max_quantity": "100000", "multiplier": "1"},
    "BTCUSDT": {"id": "BTCUSDT-PERP.BINANCE", "type": "CryptoPerpetual",
                "base_currency": "BTC", "quote_currency": "USDT", "settlement_currency": "USDT",
                "is_inverse": False, "price_increment": 0.10, "size_increment": 0.001,
                "lot_size": "0.001", "maker_fee": 0.0002, "taker_fee": 0.0005,
                "margin_init": 0.1, "margin_maint": 0.1, "min_notional": "50.00000000 USDT",
                "max_quantity": "1000", "multiplier": "1"},
    "ETHUSDT": {"id": "ETHUSDT-PERP.BINANCE", "type": "CryptoPerpetual",
                "base_currency": "ETH", "quote_currency": "USDT", "settlement_currency": "USDT",
                "is_inverse": False, "price_increment": 0.01, "size_increment": 0.001,
                "lot_size": "0.001", "maker_fee": 0.0002, "taker_fee": 0.0005,
                "margin_init": 0.1, "margin_maint": 0.1, "min_notional": "20.00000000 USDT",
                "max_quantity": "10000", "multiplier": "1"},
    "SOLUSDT": {"id": "SOLUSDT-PERP.BINANCE", "type": "CryptoPerpetual",
                "base_currency": "SOL", "quote_currency": "USDT", "settlement_currency": "USDT",
                "is_inverse": False, "price_increment": 0.0100, "size_increment": 0.01,
                "lot_size": "0.01", "maker_fee": 0.0002, "taker_fee": 0.0005,
                "margin_init": 0.1, "margin_maint": 0.1, "min_notional": "5.00000000 USDT",
                "max_quantity": "1000000", "multiplier": "1"},
}
CASE_NAMES = list(C.CASE_NAMES)


def _chain():
    return ("the record's signal semantics (a 12-state price x volume discretisation of a "
            "completed higher-timeframe bar, an empirical transition matrix over state "
            "sequences of length sequence_length, a buy signal when the bullish transition "
            "probability exceeds min_signal_probability, a sell signal on a bearish expected "
            "transition, and an opposite-signal exit taken ONLY while the position is "
            "profitable) are preserved verbatim; the alignment instant at which a state "
            "becomes available, the ATR and volume-SMA conventions, the point-in-time "
            "training of the matrix and the entry/exit fill instants are the details the "
            "record itself lists as NOT recoverable - and in the 4h case as materially "
            "defective (left-edge resample + backward as-of merge) - and are therefore "
            "registered here as an explicitly RESEARCH_DEFINED adapted contract, chosen "
            "before any computation and never adjusted afterwards")


def round_spec(fp_input, fp_value):
    return {
        "schema_version": 1,
        "document_kind": "round-spec (instantiated production pre-registration; every "
                         "scientific field is copied verbatim from the frozen "
                         "strategy_h_v1_round_spec.template.json and only the three registered "
                         "placeholders, the TO_BE_RECOMPUTED fingerprint and the template-era "
                         "implementation-status prose were substituted)",
        "template_instantiation": {
            "placeholders": list(ROUND_PLACEHOLDERS),
            "rule": "Every scientific field in this template is FROZEN before the first run. "
                    "Instantiation may only substitute the three placeholders; it must not touch "
                    "the domains, the split, the selector/disposition versions, the gates, the "
                    "registered family-level falsification landings or the falsification list "
                    "(contract INV-4).",
            "instantiated_to": "/results/<family_id>/rounds/<round_id>/round-spec.json",
            "validated_by": "python3 runtime/strategy_h_v1_counts.py --spec "
                            "runtime/templates/strategy_h_v1_round_spec.template.json",
            "status": "PREREGISTRATION ONLY / NOT LAUNCHED until the production card "
                      "instantiates it"},
        "family_id": FAMILY_ID,
        "family_title": "Production candidate - Markov chain volume-price state transitions on "
                        "Binance USD-M perpetuals (four-contract cohort panel; causal 4h state "
                        "layer over the 1h base grid), adapted portability",
        "round_id": "{{round_id}}",
        "kanban_task_id": "{{kanban_task_id}}",
        "kanban_board": "quant-strategy-research",
        "created_at_utc": "{{created_at_utc}}",
        "authored_by": "Hermes default (Xiaoqian) - contract 14.4 production handoff card",
        "contract": "QUANT_RUNTIME_PIPELINE_IMPLEMENTATION_CONTRACT.md v1.9.0 (cohort survivor "
                    "semantics of sections 7.2 / 7.3; the v1.8 launch gate additionally requires "
                    "this document's generic parameter_contract, which is generated below from "
                    "the domains registered here)",
        "semantic_fingerprint": {
            "fingerprint_input": fp_input,
            "semantic_fingerprint": fp_value,
            "normalisation": "The frozen handoff value (contract 14.2 step 7 / 14.4): family_id "
                             "| universe portability token | DCA domain (axes alphabetically) | "
                             "window | selector;disposition version | source. It was written "
                             "into the immutable /results family.json by the automatic "
                             "production handoff and is copied here VERBATIM; this template "
                             "never rewrites it.",
        },
        "parent_family": None,
        "lineage_note": "Independent family canonicalized during the contract-14.4 backlog "
                        "backfill (card t_86d04b09) from the already-reviewed wiki record "
                        "quant/markov-chain-volume-price-state-2026-08-31.md. Kanban parent edge "
                        "is scheduling/order only; scientific lineage is null: "
                        "parent_family=null - this family does not refine, inherit parameters "
                        "from, or shrink the universe of any earlier family.",
        "provenance": {
            "record": "wiki brain quant/markov-chain-volume-price-state-2026-08-31.md",
            "record_status": "research-only / implementation_status=not-implemented / "
                             "adoption=not-approved / approval_scope=research-only / "
                             "contested=true (the record carries an explicit contradiction on the "
                             "source's 4h timestamp alignment)",
            "primary_sources": ["https://github.com/jehumtine/markov-chain-trading-strategy",
                                "https://github.com/jehumtine/markov-chain-trading-strategy/blob/"
                                "11286554f829529a3c9a4dfb6439a1decbec42b9/data_processor.py",
                                "https://github.com/jehumtine/markov-chain-trading-strategy/blob/"
                                "11286554f829529a3c9a4dfb6439a1decbec42b9/backtester.py",
                                "https://github.com/jehumtine/markov-chain-trading-strategy/blob/"
                                "11286554f829529a3c9a4dfb6439a1decbec42b9/main.py"],
            "pinned_commit": "11286554f829529a3c9a4dfb6439a1decbec42b9",
            "portability": "the record's own crypto portability line is `direct` for "
                           "cryptocurrency OHLCV (\"consumes cryptocurrency OHLCV files but does "
                           "not establish a venue/contract-type requirement; Spot vs perpetual "
                           "portability must be tested rather than assumed\"). The canonical raw "
                           "store holds exactly four BINANCE USD-M perpetual contracts, all four "
                           "are registered, and the spot leg of the portability question is "
                           "disclosed as untested - never silently assumed. The record's "
                           "reported evidence (SOL/USDT 1h, Sharpe 2.91, 111 trades over five "
                           "years) is DISCLOSED, NOT CLAIMED: this round registers the "
                           "mechanism, not that result, and the record itself warns that the "
                           "README claim must not be attributed to the pinned default run.",
            "adapted_port_disclosure": _chain(),
            "superseded_with_disclosure": {
                "source_items": "sl_multiplier / tp_multiplier (the source's ATR-anchored "
                                "stop-loss and take-profit multiples) and the source's "
                                "equal-division position sizing",
                "replacement": "the card-mandated DCA execution layer: the four-axis DCA domain "
                               "fixes the take-profit (a rail TP at running_average_cost x "
                               "(1 +/- breakeven_tp_pct)) and the invalidation parameterisation "
                               "(a resting stop at running_average_cost x (1 -/+ "
                               "invalidation_pct)), and the 12-tranche rail fixes sizing "
                               "(base_quote x leverage per tranche at the entry fill price)",
                "status": "REGISTERED AND DISCLOSED, NOT IMPLEMENTED: no ATR-anchored "
                          "sl_multiplier/tp_multiplier is evaluated anywhere in this round, and "
                          "the source's equal-division sizing is replaced by the registered "
                          "rail. This is the same substitution the contract-14.4 card mandates "
                          "for every production family.",
            },
        },
        "hypothesis": {
            "statement": "Market behaviour can be discretised into 12 price-momentum "
                         "(ATR-normalised) x volume-regime states on a completed 4h bar, and "
                         "short sequences of those states carry non-random transition "
                         "probabilities to the NEXT state, so a sequence whose empirical "
                         "transition row is dominated by bullish next-states predicts the "
                         "immediate direction of the instrument.",
            "mechanism": "The record reports the effect as discretised state persistence: "
                         "\"useful sequences\" of states with a high probability of preceding a "
                         "specific bullish or bearish movement, trained from the instrument's "
                         "own history and read as a directional signal. This round measures "
                         "whether those transitions survive the registered costs, the four "
                         "execution stress grids and the card's DCA execution layer.",
            "direction": "SIGN of the trained transition row: p_bull > min_signal_probability "
                         "and p_bull > p_bear -> LONG; p_bear > min_signal_probability and "
                         "p_bear > p_bull -> SHORT; an exact tie or a row with fewer than 5 "
                         "observations -> no signal. On a perpetual both legs are tradable, so "
                         "the registered book is two-sided exactly as the record's buy/sell "
                         "signal rule states.",
            "source_note": "the record names eight parameters (price_state_threshold, "
                           "volume_high_multiplier, volume_low_multiplier, atr_period, "
                           "sequence_length, min_signal_probability, sl_multiplier, "
                           "tp_multiplier) and fixes no value for any of them. This round "
                           "registers three SEARCHED axes (threshold, sequence length, minimum "
                           "signal probability), five PROJECT pre-registration constants "
                           "(atr_period 14, volume_sma_period 24, the two volume multipliers, "
                           "the 5-observation row floor), two SUPERSEDED items "
                           "(sl_multiplier/tp_multiplier, disclosed above) and the "
                           "RESEARCH_DEFINED timing/availability contract.",
            "test_statistic": "the four registered cohorts (BNBUSDT / BTCUSDT / ETHUSDT / "
                              "SOLUSDT, base grid 1h): the deterministic historical-only winner "
                              "cell of each cohort is carried unchanged into OOS, the full "
                              "window, the four execution stress grids and its historical "
                              "parameter neighbourhood. The family statistic is the COUNT of "
                              "cohort survivors (0..4), never a cross-cohort median.",
        },
        "eligible_universe": {
            "symbols": list(C.SYMBOLS),
            "symbol_source": "BINANCE USD-M perpetual, canonical raw store (/data/raw, "
                             "read-only): the four contracts are the complete instrument set of "
                             "this machine's crypto raw store",
            "timeframes": [dict(tf) for tf in C.TIMEFRAMES],
            "cohort_count": C.CANONICAL["cohorts"],
            "cohort_definition": "one cohort = one (symbol, base grid) pair; the base grid is the "
                                 "bar series from which the registered 4h state bins are "
                                 "resampled and on which the signal episodes are executed. It is "
                                 "the v1.3.0 disposition unit; all four cohorts are always "
                                 "reported separately.",
            "instruments_metadata_measured_at_pre_registration": INSTRUMENTS,
            "universe_shrinkage_disclosure": "No symbol shrinkage: the record's portability line "
                                             "is `direct` and all four contracts of the raw "
                                             "store are registered, none is dropped after seeing "
                                             "results. The timeframe set is {1h} only - the "
                                             "record's tested base grid. 5m / 15m / 30m / 4h / 1d "
                                             "/ 1w exist in raw but are excluded BEFORE any "
                                             "computation, because the record registers 1h as "
                                             "its base grid and the registered 4h state layer is "
                                             "resampled from the cohort's OWN 1h bars rather "
                                             "than read from the raw 4h klines. The choice is "
                                             "registered before any computation and must not be "
                                             "narrowed or widened afterwards.",
            "excluded": ["5m, 15m, 30m, 4h, 1d, 1w bar grids (present in raw; the record "
                         "registers 1h as its base grid and the 4h states are a DERIVED layer, "
                         "so no raw coarser grid may enter the evaluation)",
                         "no symbol is excluded: the four registered contracts are the complete "
                         "USD-M perpetual instrument set of the canonical raw store"],
            "universe_immutability": "Registered here, before computation. Must not be narrowed "
                                     "or widened after seeing results (contract 7.2).",
        },
        "parameter_domain": {
            "kind": "strategy parameter domain (the registered state-case set), a composite axis "
                    "over (price state threshold, sequence length, minimum signal probability)",
            "case_definition": "a strategy case is (price_state_threshold, sequence_length, "
                               "min_signal_probability): the ATR-relative price-move threshold "
                               "that discretises the price state, the number of completed 4h "
                               "bin states in the decision sequence, and the probability floor "
                               "a trained transition row must exceed to emit a signal",
            "grid_cases": GRID_CASES,
            "grid_case_names": CASE_NAMES,
            "legal_cases_per_cohort": C.CANONICAL["strategy_cases"],
            "price_state_threshold_grid": list(C.PRICE_STATE_THRESHOLDS),
            "price_state_threshold_status": C.SEARCH_STATUS + " - this axis IS searched over the "
                                                              "three registered ATR-relative "
                                                              "thresholds (1.0 / 1.5 / 2.0); the "
                                                              "record names the parameter and "
                                                              "fixes no value, and it is NOT "
                                                              "user-fixed (no operator evidence "
                                                              "fixes it).",
            "sequence_length_grid": list(C.SEQUENCE_LENGTHS),
            "sequence_length_status": C.SEARCH_STATUS + " - this axis IS searched over the three "
                                                        "registered sequence lengths (1 / 2 / 3 "
                                                        "completed bin states); the record names "
                                                        "the parameter and fixes no value.",
            "min_signal_probability_grid": list(C.MIN_SIGNAL_PROBABILITIES),
            "min_signal_probability_status": C.SEARCH_STATUS + " - this axis IS searched over "
                                                               "the three registered probability "
                                                               "floors (0.5 / 0.6 / 0.7); the "
                                                               "record names the parameter and "
                                                               "fixes no value.",
            "markov_contract": C.MARKOV_CONTRACT,
            "markov_contract_status": C.RESEARCH_MARKER + " - the record fixes the MECHANISM "
                                                          "(12 states, an empirical transition "
                                                          "matrix over state sequences, a "
                                                          "probability threshold, a "
                                                          "profitability-gated opposite-signal "
                                                          "exit) and none of its timing, "
                                                          "alignment or training-window detail; "
                                                          "this contract is registered once, "
                                                          "applied identically to all four "
                                                          "cohorts, and never adjusted after "
                                                          "seeing results.",
            "state_availability_status": C.RESEARCH_MARKER + " - the record's source attaches a "
                                                             "4h bin's OWN eventual state to the "
                                                             "lower-timeframe bars inside that "
                                                             "bin (left-edge resample + backward "
                                                             "as-of merge) and the record's "
                                                             "crypto caveat requires any "
                                                             "reproduction to correct that "
                                                             "availability timing and separately "
                                                             "test the look-ahead risk. The "
                                                             "registered mapping attaches only "
                                                             "COMPLETED bin states, carries a "
                                                             "structural counter "
                                                             "(attached_state_before_availability "
                                                             "== 0) and the engine self-check "
                                                             "red-proves that the naive "
                                                             "left-edge variant is detected.",
            "entry_timing_status": C.RESEARCH_MARKER + " - the record's backtester executes at "
                                                       "the row after the evaluated sequence; "
                                                       "the registered entry is the OPEN of the "
                                                       "next base bar after a FRESH signal "
                                                       "event (the first executable price after "
                                                       "the signal is measurable), and the "
                                                       "entry_delay_1_bar stress re-measures "
                                                       "the whole product one bar later.",
            "exit_timing_status": C.RESEARCH_MARKER + " - the record's exit is 'opposite signal "
                                                      "AND currently profitable' plus "
                                                      "ATR-anchored stop/take-profit with "
                                                      "intra-bar precision. The registered exit "
                                                      "set is the DCA rail TP, the resting "
                                                      "invalidation, the record's own "
                                                      "profitability-gated opposite-signal "
                                                      "flatten at the next base bar open, and "
                                                      "the reduce-only slice-end flatten at the "
                                                      "last bar close.",
            "matrix_training_status": C.RESEARCH_MARKER + " - the record requires transition-"
                                                          "matrix training to remain strictly "
                                                          "isolated from the evaluation window; "
                                                          "the registered matrix is an "
                                                          "expanding-window point-in-time count "
                                                          "structure fed only by transitions "
                                                          "whose outcome bin has already "
                                                          "completed at the decision bar - never "
                                                          "a random split, never a refit on the "
                                                          "evaluated slice, nothing from the "
                                                          "future of the decision bar.",
            "atr_period_status": C.CONSTANT_STATUS + " - the record names atr_period and fixes no "
                                                     "value; the frozen 14 is a project "
                                                     "pre-registration constant (Wilder's "
                                                     "standard), fixed before any computation "
                                                     "and NOT a searched axis.",
            "volume_sma_period_status": C.CONSTANT_STATUS + " - the record's own text fixes the "
                                                            "rolling 24-period volume SMA; it is "
                                                            "a mechanism constant of the "
                                                            "registered state layer, frozen here "
                                                            "as a project pre-registration "
                                                            "constant (NOT searched, NOT "
                                                            "user-fixed).",
            "volume_high_multiplier_status": C.CONSTANT_STATUS + " - the record names "
                                                                 "volume_high_multiplier and "
                                                                 "fixes no value; the frozen 1.5 is "
                                                                 "a project pre-registration "
                                                                 "constant.",
            "volume_low_multiplier_status": C.CONSTANT_STATUS + " - the record names "
                                                                "volume_low_multiplier and fixes "
                                                                "no value; the frozen 0.5 is a "
                                                                "project pre-registration "
                                                                "constant.",
            "min_row_observations_status": C.CONSTANT_STATUS + " - the record registers no "
                                                               "minimum observation floor for a "
                                                               "transition row; the frozen 5 "
                                                               "observed transitions (a row with "
                                                               "fewer yields NO signal) is a "
                                                               "project pre-registration "
                                                               "constant, fixed before the first "
                                                               "run and never lowered.",
            "constants": C.MARKOV_CONSTANTS,
            "selection_rule": "The cohort winner is elected on the HISTORICAL window only "
                              "(deterministic selector, contract 7.3); OOS selects nothing and "
                              "is never read by the selector or the neighbourhood test.",
        },
        "dca_domain": {
            "kind": "DCA parameter domain (the execution rail), four axes - contract 7.2 item 4",
            "base_quote": 1000,
            "base_quote_status": C.CONSTANT_STATUS + " - held constant across the whole domain "
                                                     "(it is NOT a search axis) and NOT a "
                                                     "user-fixed invariant: no operator evidence "
                                                     "fixes it at 1000. It is a project "
                                                     "pre-registration choice, frozen here "
                                                     "before any computation (contract 7.2 "
                                                     "v1.3.1).",
            "spacing_pct": list(C.DCA_GRID["spacing_pct"]),
            "spacing_pct_status": C.SEARCH_STATUS + " - this axis IS searched over the registered "
                                                    "values; it is a pre-registered search "
                                                    "DOMAIN of this round, not an immutable "
                                                    "user-fixed invariant (contract 7.2 v1.3.1).",
            "size_multiplier": list(C.DCA_GRID["size_multiplier"]),
            "size_multiplier_status": C.SEARCH_STATUS + " - this axis IS searched over the "
                                                        "registered values (1.1 is the "
                                                        "historical progression value and a "
                                                        "search candidate here, not an "
                                                        "invariant).",
            "breakeven_tp_pct": list(C.DCA_GRID["breakeven_tp_pct"]),
            "breakeven_tp_pct_status": C.SEARCH_STATUS + " - this axis IS searched over the "
                                                         "registered values.",
            "invalidation_pct": list(C.DCA_GRID["invalidation_pct"]),
            "invalidation_pct_status": C.SEARCH_STATUS + " - this axis IS searched over the "
                                                         "registered values.",
            "config_count": C.CANONICAL["dca_configs"],
            "grid": DCA_CELLS,
            "grid_note": "the complete 4 x 2 x 3 x 2 = 48-cell product; every cell is evaluated "
                         "with true order/fill accounting on every registered phase grid",
        },
        "dca_execution_semantics": {
            "authorization": "Inherited verbatim from the Strategy A/B engine family (the ladder "
                             "geometry, breakeven-anchored TP and resting invalidation "
                             "semantics); this round parametrises the four axes and bounds the "
                             "rail by the signal episode - it does not re-interpret the "
                             "execution semantics.",
            "trigger_anchoring": "the LADDER is anchored on the INITIAL ENTRY FILL PRICE of the "
                                 "episode",
            "invalidation_anchoring": "the resting invalidation is anchored on the running "
                                      "AVERAGE COST, the same reference as the "
                                      "breakeven-anchored TP",
            "window_bounded": "tranche #1 is the initial entry at the open of the first base bar "
                              "after the fresh signal event; adverse-price scale-ins follow the "
                              "ladder while the position is open (level_k price = "
                              "initial_entry_price x (1 -/+ spacing_pct x k), k = 1..10, so at "
                              "most 11 routine active levels of the 12-tranche rail); any of the "
                              "four registered exits flattens every layer exactly once, then the "
                              "book is FLAT and no layer may be added again before a NEW fresh "
                              "signal",
            "engine_semantics": {
                "entry": "the OPEN of the first base bar after the fresh signal event, taker "
                         "fill with adverse slippage; the entry bar must lie inside the "
                         "evaluated slice or the event is skipped and counted",
                "sizing": "non-compounding fixed-quote basis on the pre-registered starting "
                          "equity: level k margin = base_quote x size_multiplier^k (k = 0..10); "
                          "level notional = margin x leverage",
                "take_profit": "reduce-only full flatten of the whole episode when the bar "
                               "high/low reaches running_average_cost x (1 +/- "
                               "breakeven_tp_pct)",
                "invalidation": "a RESTING stop at running_average_cost x (1 -/+ "
                                "invalidation_pct), anchored on the same reference as the TP",
                "signal_exit": "the record's own exit: an opposite signal while the mark price "
                               "is strictly better than the running average cost for the "
                               "position direction flattens every layer reduce-only at the next "
                               "base bar open; an opposite signal while the position is NOT "
                               "profitable is blocked and counted "
                               "(signal_exit_blocked_unprofitable) - this asymmetry is measured "
                               "by the registered family-level reader, never silently repaired",
                "slice_end": "a reduce-only flatten of every layer at the last bar close of the "
                             "evaluated slice",
                "intrabar_ordering": "deterministic and conservative: a long episode walks the "
                                     "bar LOW first and then the HIGH; a short episode mirrors "
                                     "it (HIGH first). A ladder level below (above) the resting "
                                     "stop of a long (short) can never fill, and a gap through "
                                     "the stop fills at the bar open.",
                "capital_exhaustion": "no episode is opened once the realised equity is gone; "
                                      "the guard is re-evaluated after every fill and against "
                                      "the equity the entry fee itself will leave behind",
                "non_overlap": "one position at a time: an entry event that lands while an "
                               "episode is open cannot open a second position, and the next "
                               "episode may only start from a fresh signal at a base bar "
                               "strictly after the previous flatten bar (no same-bar "
                               "re-entry); the counters can never be negative",
            },
        },
        "selector_and_disposition": {
            "selector_version": "cohort-selector-v1",
            "disposition_version": "cohort-disposition-v1",
            "selection_protocol": "Deterministic, historical window ONLY; OOS must never be used "
                                  "to select parameters.",
            "selection_steps": [
                "1. Sufficiency: if the cohort's best historical case has fewer episodes than "
                "gates.min_episodes_is, the cohort is culled with reason insufficient_trades.",
                "2. Eligibility: a case is a candidate iff historical net_pnl > 0 AND historical "
                "sharpe > 0 AND historical episodes >= gates.min_episodes_is.",
                "3. If no case is a candidate, the cohort is culled with reason "
                "no_qualifying_candidate.",
                "4. Ranking: Sharpe descending, then net_pnl descending, then a fixed lexical "
                "tie-break over the REGISTERED INDEX of each axis in the fixed order "
                "(window_case, spacing_pct, size_multiplier, breakeven_tp_pct, invalidation_pct). "
                "The first case is the cohort winner.",
                "5. The winner's exact strategy+DCA cell is carried unchanged into OOS, full, "
                "every robustness grid and the neighbourhood test. No cell may be swapped after "
                "OOS has been seen."],
            "cohort_survivor_requirements": [
                "a) a historical winner exists (steps 1-4)",
                "b) OOS: net_pnl > 0 AND sharpe > 0 for the winner's cell",
                "c) full window: net_pnl > 0 for the winner's cell",
                "d) robustness: the SAME winner cell has net_pnl > 0 in each of fee_2x, "
                "funding_2x, entry_delay_1_bar, slippage_2ticks",
                "e) parameter neighbourhood: at least 60% of the winner cell's legal "
                "face-adjacent neighbours in the registered joint space agree with the winner's "
                "HISTORICAL net-PnL sign"],
            "cull_reasons_vocabulary": ["insufficient_trades", "no_qualifying_candidate",
                                        "oos_economic", "full_economic",
                                        "robustness_economic:<grids>",
                                        "parameter_neighbourhood"],
            "family_disposition_rule": "0 cohort survivors -> verdict REJECT "
                                       "(performance_claimable=false); >=1 survivors -> verdict "
                                       "PASS (band SURVIVOR_FOUND / MULTIPLE_SURVIVORS describes "
                                       "the count only; every survivor is kept and advances); "
                                       "coverage or technical incompleteness -> "
                                       "TECHNICAL_INCOMPLETE. The survivor count is never a "
                                       "reason for performance_claimable=false (contract 9.6 is "
                                       "the only reference).",
            "runner_role": "the runner's disposition / verdict_recommendation are RECOMMENDATIONS; "
                           "the final verdict is written by default into verdict.json per "
                           "contract 10.7.",
        },
        "registered_family_level_falsification": {
            "note": "Four FAMILY-level readers registered before the first run, one per "
                    "record-named falsification item and limitation. They never cull a cohort by "
                    "themselves; a reader hit must NEVER be recorded as PASS (the runner "
                    "recommends DEFERRED and the evidence decides the final verdict).",
            "transition-matrix-stability": {
                "reader": "transition_matrix_stability",
                "definition": "from the winner's registered state layer over the HISTORICAL "
                              "window only, split the completed bins into two disjoint halves, "
                              "build both count matrices, and report (a) the max absolute "
                              "deviation of p_bull over the sequences that carry at least "
                              "min_observations_per_half = 10 observed transitions in EACH half "
                              "(a deviation measured on thinner rows is not evidence of "
                              "instability and is excluded; the reader needs at least 3 such "
                              "comparable sequences, otherwise the deviation part reports "
                              "insufficient_evidence and does not trigger), and (b) the share of "
                              "the winner's decision bars whose transition row is untrained "
                              "(fewer than 5 observations); TRIGGERED if the evidence-sufficient "
                              "max_abs_pbull_deviation > 0.25 or untrained_share > 0.5",
                "record_item": "the record's falsification item 'verify if transition "
                               "probabilities are stable over time or if the matrix requires "
                               "constant refitting'",
                "landing": "family-level: a hit must NEVER be recorded as PASS"},
            "exit-asymmetry": {
                "reader": "exit_asymmetry",
                "definition": "blocked opposite-signal exits / total opposite-signal exits over "
                              "the FULL window; TRIGGERED if the blocked share >= 0.5; also "
                              "reports the winner's win rate and mean hold",
                "record_item": "the record's falsification item 'stress test the exit on sell "
                               "signal only if profitable rule, as it acts as an asymmetrical "
                               "holding mechanism that may heavily skew win rate'",
                "landing": "family-level: a hit must NEVER be recorded as PASS"},
            "cost-boundary": {
                "reader": "cost_boundary",
                "definition": "share of cohorts whose winner's FULL-window net-PnL sign flips "
                              "against the registered cost_attrition_40bps grid; TRIGGERED if "
                              "that share > 0",
                "record_item": "the record's cost/robustness caveat and the machine's registered "
                               "40 bps-per-fill attrition stress",
                "landing": "family-level: a hit must NEVER be recorded as PASS"},
            "cross-asset-dispersion": {
                "reader": "cross_asset_dispersion",
                "definition": "share of the four cohorts whose historical winner has net_pnl > 0; "
                              "TRIGGERED if < 0.5",
                "record_item": "the record's limitation 'underspecified robustness of transition "
                               "probabilities across different assets'",
                "landing": "family-level: a hit must NEVER be recorded as PASS"},
            "disclosed_not_evaluated_round_items": [
                {"record_item": "the record's falsification item 'construct an explicit tracked "
                                "strategy-family implementation and evaluate it in "
                                "NautilusTrader'",
                 "reason": "the registered engine is the only backtester of this machine's "
                           "pipeline (no Nautilus runtime, gate or performance truth is used); "
                           "cross-implementation replication is therefore not evaluable in this "
                           "round",
                 "landing": "never PASS-bearing, never a cull"},
                {"record_item": "the record's portability clause 'Spot vs perpetual portability "
                                "must be tested rather than assumed'",
                 "reason": "the canonical raw store holds USD-M perpetuals only; the spot leg "
                           "does not exist in this machine's raw, so the perpetual leg is "
                           "registered and the spot leg is disclosed as untested",
                 "landing": "never PASS-bearing, never a cull"}],
        },
        "gates": {
            "G1_coverage": "every one of the 10 registered phase grids must contain exactly 5184 "
                           "cases (4 cohorts x 27 strategy cases x 48 DCA configs), the measured "
                           "strategy/DCA cell sets must equal the registered products, and the "
                           "case-evaluation total must equal 51840; otherwise TECHNICAL_INCOMPLETE "
                           "and no cohort is judged",
            "G2_insufficient_trades": "per cohort: fewer than min_episodes_is (30) historical "
                                      "episodes in the cohort's best case, or fewer than "
                                      "min_episodes_oos (10) episodes in the elected winner's "
                                      "OOS slice, culls the cohort (insufficient_trades)",
            "G3_cohort_selector": "historical net_pnl > 0 AND sharpe > 0 AND episodes >= 30, "
                                  "ranked by Sharpe desc, net_pnl desc, registered-index lexical "
                                  "tie-break",
            "G4_cohort_oos": "OOS net_pnl > 0 AND OOS sharpe > 0 for the frozen winner cell",
            "G5_cohort_full": "full-window net_pnl > 0 for the frozen winner cell",
            "G6_cohort_robustness": "the winner cell has net_pnl > 0 in all four execution stress "
                                    "reruns",
            "G7_cohort_neighbourhood": "at least 60% of legal face-adjacent neighbours agree in "
                                       "historical net-PnL sign",
            "verdict_rule": "TECHNICAL_INCOMPLETE if G1 fails; else each cohort passing G3-G7 is "
                            "a SURVIVOR: 0 survivors -> REJECT, >=1 survivors -> PASS (band "
                            "SURVIVOR_FOUND / MULTIPLE_SURVIVORS describes the count only). The "
                            "four registered family-level readers can only move a PASS to "
                            "DEFERRED, never to PASS.",
            "min_episodes_is": C.GATES["min_episodes_is"],
            "min_episodes_is_provenance": "RESEARCH_DEFINED - the record registers no explicit "
                                          "no-signal / insufficient-trade threshold. Its own "
                                          "evidence reports 111 trades over five years on 1h "
                                          "data (a very selective signal), so this round "
                                          "registers 30 historical episodes for the selection "
                                          "window and 10 for the OOS slice before the first run "
                                          "and never lowers them.",
            "min_episodes_oos": C.GATES["min_episodes_oos"],
            "neighborhood_min_same_sign_fraction": C.GATES["neighborhood_min_same_sign_fraction"],
            "cost_attrition_role": "the 40 bps cost_attrition_40bps grid is registered as a "
                                   "family-level reader (cost-boundary), NOT as an extra cohort "
                                   "cull: the card's registered survivor requirements are the "
                                   "four execution stress grids, and this round does not add a "
                                   "stricter cull that the registration did not ask for.",
            "known_gate_set_limitation": "the registered gate set contains no benchmark-relative "
                                         "test and no buy-and-hold comparison; a two-sided "
                                         "signal book can show positive PnL in a trending sample "
                                         "through posture alone. This limitation is disclosed and "
                                         "is not repaired inside this round.",
        },
        "metrics_definitions": {
            "equity": "30000 + cumulative realised net PnL (USDT); unrealised marked at bar "
                      "closes",
            "daily_series": "end-of-UTC-day equity marks, forward-filled across flat stretches",
            "sharpe": "mean/std (ddof=1) of daily returns x sqrt(365); risk-free 0",
            "max_dd": "peak-to-trough of the daily equity series, reported in % and USDT",
            "cagr": "(ending_equity / 30000) ^ (1/years) - 1, years from the actual bar span",
            "max_effective_leverage": "max of (position notional / unrealised equity), sampled "
                                      "every in-market bar",
            "capital_utilization": "mean of (deployed margin / unrealised equity) over "
                                   "in-market bars",
            "turnover": "sum of |fill notional| over every entry / DCA add / exit fill of the "
                        "cell",
            "dca_layer_histogram": "count of fills per ladder level, aggregated over all "
                                   "full-window base cases; direct evidence of how much of the "
                                   "12-tranche rail is reachable under resting-stop sequencing",
            "cohort_winner": "the historical-only selector output for each (symbol, base grid) "
                             "cohort",
            "windows_seen": "fresh signal entry events whose entry bar lies inside the evaluated "
                            "slice - the H analogue of a session count, because the episode "
                            "source of this family is the SIGNAL LAYER, not a time window. The "
                            "name is kept so the parameter contract's row fields stay stable",
            "windows_entered": "episodes actually opened (a fresh event with an executable entry "
                               "bar inside the slice and no capital-exhaustion refusal)",
        },
        "robustness_plan": {
            "declared_before_first_run": True,
            "must_not_narrow_universe_or_lower_gates": True,
            "items": [
                {"id": "R1", "name": "parameter-neighbourhood robustness",
                 "method": "for each cohort winner, compare the winner's historical net-PnL sign "
                           "against its legal face-adjacent neighbours in the registered joint "
                           "space (window_case, spacing_pct, size_multiplier, breakeven_tp_pct, "
                           "invalidation_pct); require >= 60% sign agreement; historical rows "
                           "only"},
                {"id": "R2", "name": "execution stress reruns",
                 "method": "full-window evaluation of all registered cells under fee_2x, "
                           "funding_2x, entry_delay_1_bar, slippage_2ticks; the winner's cell "
                           "must stay net_pnl > 0 in all four"},
                {"id": "R3", "name": "funding baseline diagnostics",
                 "method": "no_funding (historical window) and no_funding_full (full window) "
                           "grids for all cells; descriptive only, never a gate"},
                {"id": "R4", "name": "cost attrition (registered reader)",
                 "method": "cost_attrition_40bps grid for all cells; the winner's full-window "
                           "net-PnL sign is compared with the canonical track as the "
                           "family-level cost-boundary reader"},
                {"id": "R5", "name": "transition-matrix stability and exit asymmetry",
                 "method": "the record's two named falsification items, measured on the winner's "
                           "registered state layer (historical split-half matrix deviation, "
                           "untrained-row share) and on the FULL window (blocked vs taken "
                           "opposite-signal exits); family-level readers, never PASS"},
                {"id": "R6", "name": "cross-asset dispersion",
                 "method": "the share of the four cohorts whose historical winner has net_pnl > "
                           "0, against the record's 'underspecified robustness of transition "
                           "probabilities across different assets' limitation; family-level "
                           "reader, never PASS"},
            ],
        },
        "data": {
            "source": "/data/raw (host <EXPANSION>/market-data-raw), read-only",
            "venue": "BINANCE USD-M perpetual",
            "data_start": C.DATA["start"],
            "data_end": C.DATA["end"],
            "historical_start": C.DATA["historical_start"],
            "historical_end": C.DATA["historical_end"],
            "oos_start": C.DATA["oos_start"],
            "oos_end": C.DATA["oos_end"],
            "split_immutability": "The split is immutable and fixed here, before any "
                                  "computation; it must not be moved afterwards.",
            "derived_store": "Built per attempt from raw into the rebuildable /qlib/work area "
                             "(WORK_ROOT /qlib/work/strategyD-v1) via upstream qlib dump_bin.py; "
                             "read back exclusively through the qlib data layer. Never written "
                             "to /results. Bars are never resampled, gap-filled or "
                             "interpolated: a missing bar stays missing and fails the run "
                             "closed. The registered 4h state layer is resampled from the "
                             "cohort's OWN 1h bars inside the engine; the raw 4h klines are "
                             "never opened.",
            "bar_labelling": {
                "raw_field": "open_time_ms",
                "status": "VERIFIED at pre-registration on the canonical raw store",
                "measured_at_pre_registration": {
                    "grids": {"1h": {"symbols_measured": 4, "bars_in_window": 41160,
                                     "expected_if_contiguous": 41160, "off_grid_steps": 0,
                                     "missing_bars_total": 0, "close_time_delta_ms": 3599999,
                                     "reported_per_symbol": True}},
                    "state_bins": {"bin_hours": 4, "base_bars_per_bin": 4,
                                   "bins_in_window": 10290, "bins_with_exactly_4_bars": 10290,
                                   "bins_with_a_bar_count_other_than_4": 0,
                                   "first_bin_open_utc": "2022-01-01T00:00:00Z",
                                   "last_bin_open_utc": "2026-09-11T20:00:00Z",
                                   "reported_per_symbol": True},
                    "first_bar_open_utc": "2022-01-01T00:00:00Z",
                    "last_bar_close_utc": "2026-09-11T23:59:59Z",
                    "finding": "open_time_ms is the bar START in UTC and the 1h grid is exactly "
                               "contiguous for all four contracts over the window (41,160 bars "
                               "each, zero gaps, zero off-grid steps), so the bin membership of "
                               "a bar is exact: 41,160 / 4 = 10,290 bins per cohort, every bin "
                               "aligned to a 00:00 UTC 4h boundary and holding exactly 4 base "
                               "bars. The engine asserts the alignment, the 4-bar completeness "
                               "and bin_available_bar == bin_last_bar + 1 at run time."},
                "consequence": "a bar's bin, a bin's close instant and the bar that first sees "
                               "the bin's state are all derived by exact integer arithmetic on "
                               "measured timestamps; no boundary is inferred from a label",
            },
            "funding_series_contract": {
                "registered_window": "2022-01-01T00:00:00Z .. 2026-09-11T23:59:59Z",
                "measured_at_pre_registration": {
                    "observations": {"BNBUSDT": 5145, "BTCUSDT": 5145, "ETHUSDT": 5145,
                                     "SOLUSDT": 5220},
                    "modelled_funding": {"BNBUSDT": 2005, "BTCUSDT": 2005, "ETHUSDT": 2005,
                                         "SOLUSDT": 2080},
                    "official": {"BNBUSDT": 3140, "BTCUSDT": 3140, "ETHUSDT": 3140,
                                 "SOLUSDT": 3140},
                    "modelled_first": "2022-01-01T00:00:00Z",
                    "modelled_last": "2023-10-31T00:00:00Z",
                    "official_first": "2023-10-31T08:00:00Z",
                    "official_last": "2026-09-11T16:00:00Z",
                    "spacing": "BNBUSDT / BTCUSDT / ETHUSDT settle on a strict 8 h grid "
                               "(consecutive gaps 28,799,969 .. 28,800,028 ms, i.e. within 31 ms "
                               "of exact); SOLUSDT additionally carries a 4 h-interval episode "
                               "from 2022-11-10T10:00:00Z to 2022-11-18T02:00:00Z (the FTX "
                               "week), so the registered charge rule is SPACING-AGNOSTIC and "
                               "makes no 8 h-grid assumption",
                },
                "engine_rule": "the position is exposed to every settlement whose raw instant "
                               "lies in the CLOSED interval [entry instant - 1 s, exit instant "
                               "+ 1 s]; each settlement is charged at its own instant on the "
                               "position notional at that instant, in bar order, exactly once",
                "no_fabrication": "the artifacts disclose the modelled/official split; no "
                                  "modelled row may be relabelled official",
            },
        },
        "costs": {
            "source": "canonical instrument metadata (raw binance/usdm/instruments/"
                      "usdm-perp-instruments.json), read at run time, never hard-coded",
            "maker_fee": C.COSTS["maker_fee"],
            "taker_fee": C.COSTS["taker_fee"],
            "margin_init": 0.1,
            "margin_maint": 0.1,
            "apply_rule": "every fill is a market order: taker fee on the full traded notional, "
                          "plus adverse slippage of baseline_slippage_ticks instrument ticks "
                          "(1 tick = price_increment). No maker fills are assumed anywhere.",
            "baseline_slippage_ticks": C.COSTS["baseline_slippage_ticks"],
            "baseline_slippage_provenance": "research assumption of this round (NOT "
                                            "user-specified); robustness re-measures it at 2 "
                                            "ticks",
            "funding": "the registered funding series is charged at each settlement inside the "
                       "episode's exposure interval (rate x position notional at that instant); "
                       "a negative rate is a CREDIT to a long position and a COST to a short. The "
                       "no_funding / no_funding_full grids re-measure the same cells with the "
                       "funding cost zeroed (descriptive), and funding_2x doubles it.",
            "funding_exposure_rule": "The position is exposed to every funding settlement whose "
                                     "raw instant lies in the CLOSED interval [entry instant - "
                                     "1 s, exit instant + 1 s]. A settlement is charged on the "
                                     "position notional at the moment of the charge: the close of "
                                     "the bar that contains it inside the episode, or the "
                                     "episode's exit fill price when it lands at the closing "
                                     "boundary. The sign follows the position. Settlements "
                                     "outside the closed interval are never charged, and the "
                                     "rule assumes no fixed settlement spacing (SOLUSDT's "
                                     "2022-11 4 h-interval episode is charged settlement by "
                                     "settlement).",
            "cost_attrition_grid": "cost_attrition_40bps applies 8x the registered taker fee = 40 "
                                   "bps per fill, the registered attrition stress of the "
                                   "original falsification battery",
            "funding_immutability": "the funding baseline must not be swapped for a modelled "
                                    "series to improve the outcome, nor vice versa",
        },
        "authorization_invariants": {
            "provenance_class": "USER_FIXED - only items with explicit operator evidence (the "
                                "operator's stated rail definition, inherited verbatim from the "
                                "A/B registration). A searched axis, a project constant, or a "
                                "signal-mechanics field must NOT be listed here (contract 7.2 "
                                "v1.3.1).",
            "starting_equity_usdt": 30000,
            "numeraire": "USDT (sole)",
            "venue": "BINANCE USD-M linear perpetual",
            "leverage": "10x (1 / margin_init)",
            "tranches": 12,
            "tranche_12": "reserve/buffer, never routinely deployed",
            "routine_active_levels": 11,
            "initial_entry_and_scale_ins": "initial entry + adverse-price scale-ins only; no "
                                           "pre-signal adds",
            "reduce_only_exit": True,
            "same_bar_multi_level_ordering": "deterministic and conservative - see "
                                             "dca_execution_semantics.engine_semantics."
                                             "intrabar_ordering",
            "no_add_after_flat_or_kill": True,
        },
        "expected": {
            "cohorts": C.CANONICAL["cohorts"],
            "strategy_cases_per_cohort": C.CANONICAL["strategy_cases"],
            "dca_configs_per_cohort": C.CANONICAL["dca_configs"],
            "base_combinations_per_cohort": C.CANONICAL["base_combinations_per_cohort"],
            "cohort_grid_kinds": list(C.COHORT_GRID_KINDS),
            "phase_grid_count": C.CANONICAL["phase_grid_count"],
            "case_evaluations_per_cohort_per_grid": C.CANONICAL["base_combinations_per_cohort"],
            "case_evaluations_per_cohort_all_grids": (C.CANONICAL["base_combinations_per_cohort"]
                                                      * C.CANONICAL["phase_grid_count"]),
            "case_evaluations_per_grid": C.CANONICAL["case_evaluations_per_grid"],
            "expected_case_evaluations": C.CANONICAL["expected_case_evaluations"],
            "arithmetic": "4 cohorts (BNBUSDT / BTCUSDT / ETHUSDT / SOLUSDT x {1h}) x 27 "
                          "registered (price_state_threshold, sequence_length, "
                          "min_signal_probability) cases x 48 DCA configs = 1296 base "
                          "combinations per cohort per phase grid; per grid 4 x 1296 = 5184 case "
                          "evaluations; x 10 phase grids = 51840 full case evaluations. A case "
                          "evaluation = one engine simulation of one joint parameter cell of the "
                          "cohort on one phase grid.",
            "runtime_expectation": {
                "basis": "measured on this machine: Strategy A v2 evaluated 103,680 cells in "
                         "1,302 s (~12.6 ms per case); Strategy D 16,128 clock-window cells in "
                         "232 s. This family is 3x the G/F class (51,840 case evaluations), and "
                         "its signal layer is cached per (cohort, case) and reused by every DCA "
                         "config and every grid, so the episode walk dominates the cost",
                "estimate": "a rough estimate of two to four hours of engine time plus the "
                            "four-cohort 1h bin rebuild - an estimate, not a guarantee",
                "status": "estimate only; the run is launched detached inside the container and "
                          "monitored from the attempt state/log, never by holding an agent turn "
                          "open",
            },
        },
        "non_goals": [
            "no parameter search beyond the registered strategy grid and the registered DCA "
            "domain",
            "no OOS-based selection of any parameter",
            "no ATR-anchored sl_multiplier/tp_multiplier (superseded by the registered rail, "
            "disclosed in provenance)",
            "no use of the raw 4h / 5m / 15m / 30m / 1d / 1w klines: the registered state layer "
            "is resampled from the cohort's own 1h bars",
            "no venue or spot replication (the raw store holds one venue and perpetuals only; "
            "disclosed, not repaired inside this round)",
            "no NautilusTrader cross-implementation replication (disclosed, not repaired inside "
            "this round)",
            "no stop-loss / take-profit beyond the registered rail",
            "no Paper or Live trading",
            "no second backtester or engine",
            "no new Manager/Service/Factory/Registry/Orchestrator/daemon/queue",
            "no legacy Nautilus runtime, gate or performance truth",
            "no narrowing or widening of the eligible universe after seeing results",
        ],
        "artifacts_required": [
            "result.json", "artifacts/cohort_results.json", "artifacts/cohort_survivors.json",
            "artifacts/assertions.json", "artifacts/dca_layer_histogram.json",
            "artifacts/state_layer.json", "artifacts/signal_layer.json",
            "artifacts/family_falsification.json", "artifacts/robustness_diagnostics.json",
            "artifacts/funding_series.json", "artifacts/input_manifest.json",
            "artifacts/bins_build.json", "artifacts/progress.json",
        ] + ["artifacts/grid_%s.csv" % g for g in C.COHORT_GRID_KINDS],
        "assertions_declared": [
            "episodes_partition", "pnl_decomposition", "coverage_complete",
            "cohort_count_matches_registered", "strategy_grid_is_registered_product",
            "dca_grid_is_registered_product", "base_combinations_per_cohort_per_grid",
            "expected_case_evaluations", "layer0_equals_episodes", "layer_histogram_nonempty",
            "no_entry_after_exhaustion", "ending_equity_floor", "selector_deterministic",
            "selector_historical_only", "bar_grid_is_contiguous",
            "no_unregistered_strategy_case", "funding_bar_never_out_of_hold",
            "no_funding_grid_is_cost_free", "fee_2x_track_is_not_a_noop",
            "funding_2x_track_is_not_a_noop", "cost_attrition_track_is_not_a_noop",
            "no_funding_track_is_cost_free", "entry_delay_track_is_not_a_noop",
            "slippage_track_is_not_a_noop", "daily_series_is_slice_scoped",
            "bin_grid_is_aligned_and_complete", "attached_state_was_available_before_bar",
            "matrix_counts_are_causal", "signal_requires_trained_row",
            "entry_bar_is_the_next_bar_after_the_signal", "signal_exit_required_profitability",
            "no_reentry_without_a_fresh_signal", "state_index_covers_the_registered_twelve",
            "lookahead_control_reported",
        ],
        "parameter_contract": {
            "parameter_contract_version": 1,
            "family_id": FAMILY_ID,
            "contract_ref": "v1.8 generic family parameter contract "
                            "(runtime/parameter_contract.py); generated from this document's "
                            "registered parameter_domain / dca_domain",
            "research_axes_ordered": (
                [{"name": "window_case", "kind": "composite", "members": list(C.CASE_FIELDS),
                  "registered_values": [list(case) for case in C.STRATEGY_CASES],
                  "row_fields": list(C.CASE_FIELDS)}]
                + [{"name": ax, "kind": "atomic", "members": [ax],
                    "registered_values": list(C.DCA_GRID[ax]), "row_fields": [ax]}
                   for ax in C.DCA_AXES]),
            "row_fields": list(C.CASE_FIELDS) + list(C.DCA_AXES),
            "composite_map": {"window_case": list(C.CASE_FIELDS)},
            "strategy_param_fields": list(C.CASE_FIELDS),
            "dca_param_fields": list(C.DCA_AXES),
            "canonical_recipe": {"sort_keys": True, "separators": [",", ":"],
                                 "ensure_ascii": False,
                                 "numeric_rule": "JSON number finite, bool excluded"},
            "row_match_recipe": {"keys": ["symbol", "timeframe"] + list(C.CASE_FIELDS)
                                 + list(C.DCA_AXES),
                                 "equality": "exact, numeric == float compare, rest bytewise"},
            "domain_cardinality": {"strategy": C.CANONICAL["strategy_cases"],
                                   "dca": C.CANONICAL["dca_configs"],
                                   "per_cohort": C.CANONICAL["base_combinations_per_cohort"]},
        },
    }


def run_spec(fp_input, fp_value):
    return {
        "schema_version": 1,
        "document_kind": "run-spec (Strategy H v1; instantiate to /results/<family_id>/rounds/"
                         "<round_id>/attempts/<run_id>/run-spec.json BEFORE launch)",
        "template_instantiation": {
            "placeholders": list(RUN_PLACEHOLDERS),
            "rule": "Domains, split, costs, gates and the selector/disposition versions are "
                    "FROZEN before the first run and must be copied from the instantiated "
                    "round-spec.json. Only the seven placeholders may be substituted. "
                    "{{script_sha256}} must be the host-side recomputed sha256 of the deployed "
                    "/scripts/80_strategy_h_run.py; {{engine_selfcheck_sha256}} the same for "
                    "/scripts/tests/test_strategy_h_engine.py, which must run (rc=0) before "
                    "launch.",
        },
        "family_id": FAMILY_ID,
        "round_id": "{{round_id}}",
        "run_id": "{{run_id}}",
        "task_id": "{{task_id}}",
        "kanban_board": "quant-strategy-research",
        "created_at_utc": "{{created_at_utc}}",
        "round_spec_path": "{{round_spec_path}}",
        "selector_version": "cohort-selector-v1",
        "disposition_version": "cohort-disposition-v1",
        "data": {"source": "/data/raw", "read_only": True, "symbols": list(C.SYMBOLS),
                 "timeframes": [dict(tf) for tf in C.TIMEFRAMES],
                 "start": C.DATA["start"], "end": C.DATA["end"],
                 "historical_start": C.DATA["historical_start"],
                 "historical_end": C.DATA["historical_end"],
                 "oos_start": C.DATA["oos_start"], "oos_end": C.DATA["oos_end"],
                 "funding_truth_status_windows": {
                     "modeled_funding": "2022-01-01T00:00:00Z .. 2023-10-31 (reconstruction; "
                                        "mark_price null)",
                     "official": "2023-10-31T08:00:00Z .. 2026-09-11T23:59:59Z (Binance mark "
                                 "price present)",
                     "primary_uses": "the complete registered series (modelled + official), as a "
                                     "COST only",
                     "engine_rule": "The position is exposed to every funding settlement whose "
                                    "raw instant lies in the CLOSED interval [entry instant - "
                                    "1 s, exit instant + 1 s]. A settlement is charged on the "
                                    "position notional at the moment of the charge: the close of "
                                    "the bar that contains it inside the episode, or the "
                                    "episode's exit fill price when it lands at the closing "
                                    "boundary. The sign follows the position: a positive rate "
                                    "is a cost to a long and a credit to a short. Settlements "
                                    "outside the closed interval are never charged, and the "
                                    "rule assumes no fixed settlement spacing (SOLUSDT's "
                                    "2022-11 4 h-interval episode is charged settlement by "
                                    "settlement)."},
                 "bar_labelling": "VERIFIED at pre-registration: open_time_ms is the bar START "
                                  "in UTC; the 1h grid is exactly contiguous for all four "
                                  "contracts over the window (41,160 bars each, 0 gaps, 0 "
                                  "off-grid steps) and 41,160 / 4 = 10,290 4h bins per cohort "
                                  "hold exactly 4 base bars each, aligned to 00:00 UTC, so the "
                                  "bin membership and the bin-close instant are exact and the "
                                  "engine asserts them at run time."},
        "parameter_domain": {"grid_cases": GRID_CASES, "grid_case_names": CASE_NAMES,
                             "legal_cases_per_cohort": C.CANONICAL["strategy_cases"],
                             "price_state_threshold_grid": list(C.PRICE_STATE_THRESHOLDS),
                             "sequence_length_grid": list(C.SEQUENCE_LENGTHS),
                             "min_signal_probability_grid": list(C.MIN_SIGNAL_PROBABILITIES),
                             "markov_contract": C.MARKOV_CONTRACT,
                             "markov_contract_status": C.RESEARCH_MARKER,
                             "state_availability_status": C.RESEARCH_MARKER,
                             "entry_timing_status": C.RESEARCH_MARKER,
                             "exit_timing_status": C.RESEARCH_MARKER,
                             "matrix_training_status": C.RESEARCH_MARKER,
                             "constants": C.MARKOV_CONSTANTS},
        "dca_domain": {"base_quote": 1000,
                       "base_quote_status": C.CONSTANT_STATUS,
                       "spacing_pct": list(C.DCA_GRID["spacing_pct"]),
                       "spacing_pct_status": C.SEARCH_STATUS,
                       "size_multiplier": list(C.DCA_GRID["size_multiplier"]),
                       "size_multiplier_status": C.SEARCH_STATUS,
                       "breakeven_tp_pct": list(C.DCA_GRID["breakeven_tp_pct"]),
                       "breakeven_tp_pct_status": C.SEARCH_STATUS,
                       "invalidation_pct": list(C.DCA_GRID["invalidation_pct"]),
                       "invalidation_pct_status": C.SEARCH_STATUS,
                       "config_count": C.CANONICAL["dca_configs"],
                       "grid": DCA_CELLS},
        "provenance_mirror": {"base_quote_status": C.CONSTANT_STATUS,
                              "spacing_pct_status": C.SEARCH_STATUS,
                              "size_multiplier_status": C.SEARCH_STATUS,
                              "breakeven_tp_pct_status": C.SEARCH_STATUS,
                              "invalidation_pct_status": C.SEARCH_STATUS},
        "gates": {"min_episodes_is": C.GATES["min_episodes_is"],
                  "min_episodes_oos": C.GATES["min_episodes_oos"],
                  "neighborhood_min_same_sign_fraction":
                      C.GATES["neighborhood_min_same_sign_fraction"]},
        "costs": {"source": "canonical instrument metadata, read at run time from /data/raw",
                  "maker_fee": C.COSTS["maker_fee"], "taker_fee": C.COSTS["taker_fee"],
                  "fee_bps": 5, "baseline_slippage_ticks": C.COSTS["baseline_slippage_ticks"],
                  "cost_attrition_fee_mult": C.COSTS["cost_attrition_fee_mult"],
                  "funding": "charged per settlement inside the episode's closed exposure "
                             "interval; funding_2x doubles it and the no_funding grids zero it "
                             "(descriptive)",
                  "funding_exposure_rule": "The position is exposed to every funding settlement "
                                           "whose raw instant lies in the CLOSED interval [entry "
                                           "instant - 1 s, exit instant + 1 s]. A settlement is "
                                           "charged on the position notional at the moment of "
                                           "the charge: the close of the bar that contains it "
                                           "inside the episode, or the episode's exit fill price "
                                           "when it lands at the closing boundary. The sign "
                                           "follows the position: a positive rate is a cost to a "
                                           "long and a credit to a short. Settlements outside "
                                           "the closed interval are never charged, and the rule "
                                           "assumes no fixed settlement spacing (SOLUSDT's "
                                           "2022-11 4 h-interval episode is charged settlement "
                                           "by settlement)."},
        "expected": {"cohorts": C.CANONICAL["cohorts"],
                     "strategy_cases_per_cohort": C.CANONICAL["strategy_cases"],
                     "dca_configs_per_cohort": C.CANONICAL["dca_configs"],
                     "base_combinations_per_cohort": C.CANONICAL["base_combinations_per_cohort"],
                     "cohort_grid_kinds": list(C.COHORT_GRID_KINDS),
                     "phase_grid_count": C.CANONICAL["phase_grid_count"],
                     "case_evaluations_per_grid": C.CANONICAL["case_evaluations_per_grid"],
                     "expected_case_evaluations": C.CANONICAL["expected_case_evaluations"]},
        "script": {"path": "/scripts/80_strategy_h_run.py", "sha256": "{{script_sha256}}",
                   "deployed_from": "HCH725/quant-runtime-pipeline "
                                    "container/scripts/80_strategy_h_run.py (byte-identical, P10 "
                                    "recomputes it host side)"},
        "engine_selfcheck": {"script": "/scripts/tests/test_strategy_h_engine.py",
                             "sha256": "{{engine_selfcheck_sha256}}",
                             "must_run_before_launch": True},
        "expected_outputs": ["result.json", "artifacts/cohort_results.json",
                             "artifacts/cohort_survivors.json", "artifacts/assertions.json",
                             "artifacts/dca_layer_histogram.json",
                             "artifacts/state_layer.json", "artifacts/signal_layer.json",
                             "artifacts/family_falsification.json",
                             "artifacts/robustness_diagnostics.json",
                             "artifacts/funding_series.json", "artifacts/input_manifest.json",
                             "artifacts/bins_build.json", "artifacts/progress.json"]
                            + ["artifacts/grid_%s.csv" % g for g in C.COHORT_GRID_KINDS],
        "falsification": [
            "no signal / insufficient entry events (G2)",
            "no qualifying historical candidate (G3)",
            "OOS economic rejection (G4)",
            "full-window economic rejection (G5)",
            "robustness economic failure (G6)",
            "parameter-neighbourhood fragility (G7)",
            "transition-matrix instability -> family-level, never PASS",
            "exit-asymmetry dominance -> family-level, never PASS",
            "cost boundary (40 bps attrition) -> family-level, never PASS",
            "cross-asset dispersion -> family-level, never PASS",
            "coverage incomplete in any registered phase grid (G1)",
            "any false assertion in assertions.json",
        ],
        "notes": "One attempt of round {{round_id}}. The engine rebuilds the qlib .bin store from "
                 "the read-only raw store, resamples each cohort's own 1h bars into causal 4h "
                 "bins, trains the transition matrix point-in-time, evaluates 4 cohorts x 27 "
                 "strategy cases x 48 DCA configs on 10 registered phase grids, and writes the "
                 "registered artifacts. The runner's verdict_recommendation is a recommendation; "
                 "the final verdict.json is written by the Hermes default card after reading the "
                 "artifacts back (contract 10.7).",
        "semantic_fingerprint": {"fingerprint_input": fp_input, "semantic_fingerprint": fp_value},
    }


def payload(doc):
    return json.dumps(doc, indent=1, ensure_ascii=False, sort_keys=True) + "\n"


def walk_strings(obj):
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, list):
        for v in obj:
            for s in walk_strings(v):
                yield s
    elif isinstance(obj, dict):
        for v in obj.values():
            for s in walk_strings(v):
                yield s


def token_audit(doc, allowed):
    """(unexpected_tokens, missing_tokens) over every string of a template."""
    seen = set()
    for s in walk_strings(doc):
        seen.update(re.findall(r"\{\{[^}]*\}\}", s))
    return sorted(seen - set(allowed)), sorted(set(allowed) - seen)


def walk_substitute(obj: Any, mapping: dict) -> Any:
    if isinstance(obj, str):
        out = obj
        for token, value in mapping.items():
            out = out.replace(token, value)
        return out
    if isinstance(obj, list):
        return [walk_substitute(v, mapping) for v in obj]
    if isinstance(obj, dict):
        return {k: walk_substitute(v, mapping) for k, v in obj.items()}
    return obj


def leftover(obj, path="$"):
    found = []
    if isinstance(obj, str):
        if "{{" in obj:
            found.append(path)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            found += leftover(v, "%s[%d]" % (path, i))
    elif isinstance(obj, dict):
        for k, v in obj.items():
            found += leftover(v, "%s.%s" % (path, k))
    return found


def instantiated_pair(round_t, run_t):
    """The pair exactly as the production card publishes it (synthetic launch-time values)."""
    mapping = {"{{round_id}}": FAMILY_ID + "-r1", "{{run_id}}": FAMILY_ID + "-r1-u1",
               "{{task_id}}": "t_template_check", "{{kanban_task_id}}": "t_template_check",
               "{{created_at_utc}}": "1970-01-01T00:00:00Z",
               "{{script_sha256}}": "sha256:" + "0" * 64,
               "{{engine_selfcheck_sha256}}": "sha256:" + "1" * 64,
               "{{round_spec_path}}": "/results/%s/rounds/%s-r1/round-spec.json"
                                      % (FAMILY_ID, FAMILY_ID)}
    round_i = dict(walk_substitute(round_t, mapping))
    run_i = dict(walk_substitute(run_t, mapping))
    fp = round_i["semantic_fingerprint"]["fingerprint_input"]
    round_i["semantic_fingerprint"]["semantic_fingerprint"] = C.fingerprint(fp)
    run_i["semantic_fingerprint"]["semantic_fingerprint"] = C.fingerprint(fp)
    return round_i, run_i


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--family-json",
                    default="/Volumes/ExpansionDrive/qlib-results/%s/family.json" % FAMILY_ID)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    fp_input, fp_value = "TO_BE_RECOMPUTED", "TO_BE_RECOMPUTED"
    if os.path.exists(args.family_json):
        fam = C.load(args.family_json)
        fp_input = fam["fingerprint_input"]
        fp_value = fam["semantic_fingerprint"]
    round_t = round_spec(fp_input, fp_value)
    run_t = run_spec(fp_input, fp_value)
    if args.check:
        problems = []
        for doc, name in ((round_t, "round"), (run_t, "run")):
            if [k for k, v in doc.items() if v is None and k != "parent_family"]:
                problems.append("%s template has empty fields: %r" % (name, sorted(
                    k for k, v in doc.items() if v is None and k != "parent_family")))
        # 1. the ONLY unsubstituted tokens may be the registered placeholders
        for doc, name, allowed in ((round_t, "round", ROUND_PLACEHOLDERS),
                                   (run_t, "run", RUN_PLACEHOLDERS)):
            unexpected, missing = token_audit(doc, allowed)
            if unexpected:
                problems.append("%s template carries unregistered token(s): %r"
                                % (name, unexpected))
            if missing:
                problems.append("%s template is missing registered placeholder(s): %r"
                                % (name, missing))
        # 2. the round template alone must satisfy the counts validator and the v1.8 launch gate
        _c, probs, _e = C.check(round_t, None)
        problems += ["round-spec: %s" % p for p in probs]
        problems += ["round-spec contract: %s" % p
                     for p in pc.validate_round_spec_contract(round_t)]
        problems += ["round-spec parameter_contract: %s" % p
                     for p in pc.validate_contract(round_t["parameter_contract"])]
        # 3. the pair exactly as the production card publishes it (the raw {{script_sha256}}
        #    cannot satisfy the sha pin check before substitution)
        round_i, run_i = instantiated_pair(round_t, run_t)
        left = leftover(round_i) + leftover(run_i)
        if left:
            problems.append("instantiated pair has unsubstituted placeholders: %r" % (left[:5],))
        _c, probs, _e = C.check(round_i, run_i)
        problems += ["instantiated: %s" % p for p in probs]
        problems += ["instantiated contract: %s" % p
                     for p in pc.validate_round_spec_contract(round_i)]
        # 4. byte stability: the regenerated documents must equal the frozen files byte for byte
        for name, doc in (("strategy_h_v1_round_spec.template.json", round_t),
                          ("strategy_h_v1_run_spec.template.json", run_t)):
            path = os.path.join(TEMPLATES, name)
            if not os.path.exists(path):
                problems.append("%s is missing (run without --check first)" % name)
            elif open(path, encoding="utf-8").read() != payload(doc):
                problems.append("%s on disk differs from the authoring source (not byte-stable)"
                                % name)
        print("template check: %d problem(s)" % len(problems))
        for p in problems:
            print("PROBLEM:", p)
        if not problems:
            print("registered counts: %d cohorts x %d strategy cases x %d DCA = %d per cohort "
                  "per grid; %d per grid; %d case evaluations"
                  % (C.CANONICAL["cohorts"], C.CANONICAL["strategy_cases"],
                     C.CANONICAL["dca_configs"], C.CANONICAL["base_combinations_per_cohort"],
                     C.CANONICAL["case_evaluations_per_grid"],
                     C.CANONICAL["expected_case_evaluations"]))
        return 1 if problems else 0
    os.makedirs(TEMPLATES, exist_ok=True)
    for name, doc in (("strategy_h_v1_round_spec.template.json", round_t),
                      ("strategy_h_v1_run_spec.template.json", run_t)):
        path = os.path.join(TEMPLATES, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(payload(doc))
        print("wrote %s (%d bytes)" % (path, os.path.getsize(path)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
